### PR TITLE
[TS] LPS-118500 | master

### PR DESCRIPTION
**Pull request by samanzanedo**
References:
https://issues.liferay.com/browse/LPS-118500

### CODE REVIEW

**Comment by samanzanedo** [comment]
ci:test:sf

**Comment by samanzanedo** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Hey @samanzanedo, thanks for sending this over!

As it so happens, we've done a bit of a restructuring in our process so that when people is on PTO (like @izaera is right now) PRs are still properly dealt with ☺️ 

Could you please go through the [Frontend Infrastructure Team code review process](https://github.com/liferay/liferay-frontend-guidelines/blob/master/dxp/code_review.md#frontend-infrastructure-team-code-review-process) and [Pull Request Etiquette](https://github.com/liferay/liferay-frontend-guidelines/blob/master/general/pull_requests.md) a little bit to adjust?

In summary:
- Send PRs for code review to @liferay-frontend
- Provide a **description**. Please, even if some of it is copied from JIRA... add some context and also some rationale as to what you did, what you tried, what you discarded or things like that when relevant
- Provide a **test plan**. Please, again, even if it's copied from JIRA... it helps a bit to keep things in context

You should be able to see some examples in the existing PRs at https://github.com/liferay-frontend/liferay-portal/pulls

Ping me if you have any doubts about this! Hope we can make this a satisfactory experience for you and your code! 🤗

**Comment by samanzanedo** [comment]
Hey @jbalsas 

Thanks a lot for the detailed explanation about frontend-related PR procedure.
It is clear and well explained.

I opened https://github.com/liferay-frontend/liferay-portal/pull/207 I hope this time I follow the correct way.

Kind regards.
 Sergio.

**Comment by samanzanedo** [comment]
See https://github.com/liferay-frontend/liferay-portal/pull/207

**Pull request closed without merging**
