### PR TITLE
LPS-70588 Add missing spaces to calc css function

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by izaera** [comment]
This is failing the same test as https://github.com/jbalsas/liferay-portal/pull/814, so it looks like a valid positive. @robertoDiaz @jbalsas

**Comment by jbalsas** [comment]
Yeah, I don't think `XMLSourceProcessorTest.testCharactersBeforeDefinitionTag`  was failing before...

**Comment by jbalsas** [comment]
ci:reopen

**Comment by jbalsas** [comment]
In fact, it is failing in brian as well: https://github.com/brianchandotcom/liferay-portal/pull/51350

**Comment by izaera** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/51363. [See changes here.](https://github.com/izaera/liferay-portal/compare/47bf537a26e4~1...47bf537a26e4) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
