### PR TITLE
chore: use liferay-npm-scripts v29.1.0

### PR DESCRIPTION
**Pull request by izaera**
This is to be able to build themes with Themes Toolkit 10

https://issues.liferay.com/browse/LPS-111039

### CODE REVIEW

**Comment by izaera** [comment]
ci:forward

**Comment by izaera** [comment]
ci:forward

**Comment by izaera** [comment]
ci:stop

**Comment by izaera** [comment]
ci:test:relevant

**Comment by izaera** [comment]
resent as https://github.com/izaera/liferay-portal/pull/136 due to CI blockage

**Comment by jkappler** [comment]
ci:close

**Comment by jkappler** [comment]
ci:stop

**Comment by wincent** [comment]
Cross-linking troubleshooting thread for posterity: https://liferay.slack.com/archives/C19PWQ74J/p1587459691266300

**Pull request closed without merging**
