### PR TITLE
LPS-85977

### PR DESCRIPTION
**Pull request by JavierMoral**
Hi @izaera ,
I don't know what's wrong with the tests but my commit just changes one line so I don't think it is the cause. I'm sending you this because the code I changed was added by you, can you take a look at it?

The problem is that, when the property 'portal.proxy.path' was set, the ProxyPath was added twice to the url of resolved modules.

If I should send the pull to anyone else please tell me.
Thanks!

### CODE REVIEW

**Comment by JavierMoral** [comment]
ci:test:relevant

**Comment by JavierMoral** [comment]
ci:reopen

**Comment by JavierMoral** [comment]
ci:stop

**Comment by JavierMoral** [comment]
ci:test

**Comment by izaera** [comment]
Pull request forwarded to https://github.com/brianchandotcom/liferay-portal/pull/63841. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
