### PR TITLE
pull-request-23316

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Ivan, please see https://github.com/brianchandotcom/liferay-portal/pull/23304

Thx

**Comment by brianchandotcom** [comment]
Ivan, please see https://github.com/brianchandotcom/liferay-portal/pull/23316

**Comment by izaera** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by izaera** [comment]
@brianchandotcom @rotty3000 I'm testing this.

**Comment by izaera** [comment]
It's working :-).

**Comment by brianchandotcom** [comment]
Thx.

**Pull request closed without merging**
