### PR TITLE
LPS-88891 Removes no longer needed explicit namespace

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by izaera** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by izaera** [comment]
Pull request submitted to https://github.com/jbalsas/liferay-portal/pull/1592. [See changes here.](https://github.com/izaera/liferay-portal/compare/06eb695838d2~3...06eb695838d2) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by yuchi** [comment]
OMG — Is **this** what *I think* it is?!

**Comment by yuchi** [comment]
Did you solve yuchi/frontend-ng-loader-workspace#7?

**Comment by jbalsas** [comment]
It might be, @yuchi, it might be! 🙏

**Comment by jbalsas** [comment]
But most definitely not, still a lot of work to do here... but starting to shape up!

**Pull request closed without merging**
