### PR TITLE
LPS-103179

### PR DESCRIPTION
**Pull request by jonathanmccann**
Resending from https://github.com/jbalsas/liferay-portal/pull/1981

https://github.com/izaera/liferay-portal/commit/40f69f088b4abdb4b93a407946e4aa497939b440 Adds a test that highlights the issue being resolved by LPS-103179 by having the trailing `rv` in the user-agent string.

https://github.com/izaera/liferay-portal/commit/48a3076fc7f7a2996dd2231ba336c69d7478c0c7 Without this the previous user-agent string and a number of others will not be run through the `testParseVersion` method. The other way to resolve this would be to remove `(khtml, like gecko)` from the user-agent string but I thought it'd be better to leave the user-agent strings as is and introduce additional logic to the test. If you see a better alternative please let me know.

https://github.com/izaera/liferay-portal/pull/114/commits/5fbe83b6ee74dadcfd6c91f3f4421df2685a5221 This is general clean up of the test.

Thank you.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by izaera** [comment]
Just started reviewing :)

**Comment by izaera** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/79681.

**Pull request closed without merging**
