### PR TITLE
LPS-83808 Sets href as empty by default as undefined values are not valid

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by izaera** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by izaera** [comment]
Pull request submitted to https://github.com/jbalsas/liferay-portal/pull/1581. [See changes here.](https://github.com/izaera/liferay-portal/compare/25ac0c828e99~1...25ac0c828e99) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
