### PR TITLE
LPS-83808 DO NOT COMMIT Stores generated randomId to make sure we don't always generate a different one

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by izaera** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by izaera** [comment]
Pull request submitted to https://github.com/jbalsas/liferay-portal/pull/1585. [See changes here.](https://github.com/izaera/liferay-portal/compare/dc0451857836~1...dc0451857836) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by izaera** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/66551. [See changes here.](https://github.com/izaera/liferay-portal/compare/57c26d959b35~3...57c26d959b35) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by izaera** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/66552. [See changes here.](https://github.com/izaera/liferay-portal/compare/f366fb7aeb81~4...f366fb7aeb81) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
