### PR TITLE
LPS-78252 Fix url to geo.json file in clay:geomap

### PR DESCRIPTION
**Pull request by julien**

### CODE REVIEW

**Comment by julien** [comment]
ci:test

**Comment by julien** [comment]
ci:retest

**Comment by izaera** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by izaera** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/55780. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
