### PR TITLE
LPS-73444

### PR DESCRIPTION
**Pull request by crodriguezy**

### CODE REVIEW

**Comment by jcampoy** [comment]
Hey @izaera , I think you do not have enabled the ci-tester in your github account. 
Best regards!

**Comment by izaera** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Thanks a lot @jcampoy, @crodriguezy!! 👏

**Comment by izaera** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/50160. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
