### PR TITLE
chore: use liferay-npm-scripts v29.1.1

### PR DESCRIPTION
**Pull request by izaera**
/CC @wincent

### CODE REVIEW

**Comment by izaera** [comment]
ci:forward

**Comment by izaera** [comment]
ci:test:relevant

**Comment by wincent** [comment]
I am not hopeful for the retry. Saw a similiar failure [over here](https://github.com/wincent/liferay-portal/pull/226#issuecomment-618358196) and [forwarded manually](https://github.com/brianchandotcom/liferay-portal/pull/87903).

**Comment by izaera** [comment]
@wincent True. Looks like an upstream error but because upstream is not accessible, it it not detected as such and fails the PR.

Intriguingly, if you click on `For upstream results, click here.` it takes you to a Jenkins page saying that the last successful build took place 2 months and 22 days ago :thinking:

**Comment by izaera** [comment]
So, this hanged or is not executing and the `Some checks haven’t completed yet` panel is lying. Apparently is the second but I'm not sure how to confirm it. I have clicked on the `Details` link of the pending job and it takes me to a finished build, thus my guess.

**Comment by izaera** [comment]
@wincent What do you want to do with this now? Forwarding it manually to Brian? Include it in another PR? I think this was a prerequisite of some other PR... :thinking:

**Comment by izaera** [comment]
I've force pushed a rebase onto today's master to be able to relaunch tests.

**Comment by izaera** [comment]
ci:forward

**Pull request closed without merging**
