### PR TITLE
LPS-74313 ant build-lang

### PR DESCRIPTION
**Pull request by jbalsas**
Hey Chema! Here comes the PR changing the taglib. The result I am lookin for can be seen below.

date-user

Let me know whether it makes sense to you!

### CODE REVIEW

**Comment by brandizzi** [comment]
ci:reopen

**Comment by izaera** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by izaera** [comment]
ci:retest

**Comment by izaera** [comment]
@brandizzi I saw that you asked about the error, should I wait until you find a fix for it or forward it to Brian? Maybe he does know something else about the error...🤔

**Comment by izaera** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
On Tue, Sep 5, 2017 at 3:57 AM, Ivan Zaera <notifications@github.com> wrote:

> @brandizzi <https://github.com/brandizzi> I saw that you asked about the
> error, should I wait until you find a fix for it or forward it to Brian?
> Maybe he does know something else about the error...🤔
>
Well, we got not definitive answer. I would send the PR to BChan. Then we
will know if there is a problem here ;)

**Comment by izaera** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/51396. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by izaera** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/51404. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
