### PR TITLE
LPS-96596 add pathProxy only once when needed

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by izaera** [comment]
Just started reviewing :)

**Comment by AngeloJ** [comment]
@jbalsas, since Ivan is on vacation until July 15th is there someone else who can review this pull?

**Comment by jbalsas** [comment]
Hey @AngeloJ, Iván was actually reviewing this for a while before leaving and wasn't confident about the changes in here. We talked and he needed some additional time to get this through and put together the proper infrastructure to try to avoid this from happening in the future.

As a patch, this should probably do the trick, so I'd suggest providing a hot-fix if a customer is waiting. If possible, I'd like to avoid committing this so we don't get trapped by these changes in the future.

**Comment by izaera** [comment]
Resent as https://github.com/ryannealeigh/liferay-portal/pull/3

**Pull request closed without merging**
