### PR TITLE
LPS-92792

### PR DESCRIPTION
**Pull request by jcampoy**

### CODE REVIEW

**Comment by jcampoy** [comment]
ci:test:relevant

**Comment by jcampoy** [comment]
ci:test:sf

**Comment by izaera** [comment]
Just started reviewing :)

**Comment by izaera** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/70367. [See changes here.](https://github.com/izaera/liferay-portal/compare/ae22e334ee5b~1...ae22e334ee5b)

**Pull request closed without merging**
