### PR TITLE
LPS-76970

### PR DESCRIPTION
**Pull request by jbalsas**
https://issues.liferay.com/browse/LPS-76970

This issue was originally managed in LPS-76620 (see previous https://github.com/jbalsas/liferay-portal/pull/932) but I have extracted frontend infrastructure section from original [LPS-76620](https://issues.liferay.com/browse/LPS-76620) to this new [LPS-76970](https://issues.liferay.com/browse/LPS-76970)

**Tests:** They were successful executed here: https://github.com/jorgediaz-lr/liferay-portal/pull/167
(Gradle error was fixed before sending this pull request)

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
Hi @jbalsas @izaera 

Do you have any update about this pr?

Thank you

**Comment by izaera** [comment]
Nope :-(. I will review it today.

**Comment by izaera** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/54464. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
