### PR TITLE
LPS-73512 Return error 400 "Bad Request" in case of wrong extension.

### PR DESCRIPTION
**Pull request by jbalsas**
Hey @jorgediaz-lr, I've resnet this to @izaera for a better review. In any case... could you please add a test to `ComboServlet` to cover this?

Thanks!

### CODE REVIEW

**Comment by izaera** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by izaera** [comment]
@jorgediaz-lr @jbalsas Looks good to me. Just send it directly to Brian after adding the test 👍 .

**Comment by jorgediaz-lr** [comment]
Hi @izaera 

I will resent pull request with new test

Thank you

**Comment by jorgediaz-lr** [comment]
ci:close

**Comment by jorgediaz-lr** [comment]
You can close this PR.

**Comment by jorgediaz-lr** [comment]
Resent in https://github.com/izaera/liferay-portal/pull/9 with tests

**Pull request closed without merging**
